apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gpu-operator-certified
  namespace: nvidia-gpu-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    operators.coreos.com/gpu-operator-certified.nvidia-gpu-operator: ''
spec:
  #TODO add in README.md that might have to be updated based on what channels are avaiable.
  channel: v25.3
  installPlanApproval: Automatic
  name: gpu-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  #TODO verify if this needs to be hardcoded or can we leave it blank
  startingCSV: gpu-operator-certified.v25.3.4 
