apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    opendatahub.io/image-display-name: Jupyter | Minimal | CPU | Python 3.12
    opendatahub.io/hardware-profile-resource-version: '790621'
    opendatahub.io/user: admin
    openshift.io/description: ''
    openshift.io/display-name: wb-gpu
    notebooks.opendatahub.io/last-image-version-git-commit-selection: d3137ca
    notebooks.opendatahub.io/last-image-selection: 's2i-minimal-notebook:3.4'
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/username: admin
    opendatahub.io/hardware-profile-name: nvidia-gpu-100
    opendatahub.io/connections: ''
    notebooks.opendatahub.io/inject-auth: 'true'
    opendatahub.io/workbench-image-namespace: ''
  resourceVersion: '795998'
  name: wb-gpu
  uid: 51cc118c-6c0a-4790-84ac-ec3ed14a26f3
  creationTimestamp: '2026-05-18T23:47:49Z'
  generation: 1
  managedFields:
    - apiVersion: kubeflow.org/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: {}
            'v:"notebook.opendatahub.io/httproute-cleanup"': {}
            'v:"notebook.opendatahub.io/kube-rbac-proxy-cleanup"': {}
            'v:"notebook.opendatahub.io/referencegrant-cleanup"': {}
      manager: manager
      operation: Update
      time: '2026-05-18T23:47:49Z'
    - apiVersion: kubeflow.org/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:opendatahub.io/hardware-profile-name': {}
            'f:opendatahub.io/connections': {}
            .: {}
            'f:opendatahub.io/image-display-name': {}
            'f:notebooks.opendatahub.io/inject-auth': {}
            'f:opendatahub.io/user': {}
            'f:opendatahub.io/workbench-image-namespace': {}
            'f:notebooks.opendatahub.io/last-image-selection': {}
            'f:openshift.io/display-name': {}
            'f:opendatahub.io/hardware-profile-namespace': {}
            'f:opendatahub.io/hardware-profile-resource-version': {}
            'f:openshift.io/description': {}
            'f:notebooks.opendatahub.io/last-image-version-git-commit-selection': {}
            'f:opendatahub.io/username': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:opendatahub.io/dashboard': {}
            'f:opendatahub.io/odh-managed': {}
        'f:spec':
          .: {}
          'f:template':
            .: {}
            'f:spec':
              .: {}
              'f:containers':
                .: {}
                'k:{"name":"wb-gpu"}':
                  'f:envFrom': {}
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/dev/shm"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/opt/app-root/src/"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                  .: {}
                  'f:workingDir': {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                      'f:nvidia.com/gpu': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                      'f:nvidia.com/gpu': {}
                  'f:livenessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:env':
                    .: {}
                    'k:{"name":"JUPYTER_IMAGE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"NOTEBOOK_ARGS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:readinessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8888,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:enableServiceLinks': {}
              'f:volumes':
                .: {}
                'k:{"name":"shm"}':
                  .: {}
                  'f:emptyDir':
                    .: {}
                    'f:medium': {}
                  'f:name': {}
                'k:{"name":"wb-gpu-storage"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
      manager: unknown
      operation: Update
      time: '2026-05-18T23:47:49Z'
    - apiVersion: kubeflow.org/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
          'f:containerState':
            .: {}
            'f:running':
              .: {}
              'f:startedAt': {}
          'f:readyReplicas': {}
      manager: manager
      operation: Update
      subresource: status
      time: '2026-05-18T23:48:43Z'
  namespace: rhoai-nonadmin-project
  finalizers:
    - notebook.opendatahub.io/httproute-cleanup
    - notebook.opendatahub.io/referencegrant-cleanup
    - notebook.opendatahub.io/kube-rbac-proxy-cleanup
  labels:
    app: wb-gpu
    opendatahub.io/dashboard: 'true'
    opendatahub.io/odh-managed: 'true'
spec:
  template:
    spec:
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 4Gi
              nvidia.com/gpu: '1'
            requests:
              cpu: '2'
              memory: 4Gi
              nvidia.com/gpu: '1'
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/rhoai-nonadmin-project/wb-gpu/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: wb-gpu
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/rhoai-nonadmin-project/wb-gpu/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                                  --ServerApp.token=''
                                  --ServerApp.password=''
                                  --ServerApp.base_url=/notebook/rhoai-nonadmin-project/wb-gpu
                                  --ServerApp.quit_button=False
            - name: JUPYTER_IMAGE
              value: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-minimal-notebook:3.4'
            - name: PIP_CERT
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: REQUESTS_CA_BUNDLE
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: SSL_CERT_FILE
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: PIPELINES_SSL_SA_CERTS
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: KF_PIPELINES_SSL_SA_CERTS
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: GIT_SSL_CAINFO
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/app-root/src/
              name: wb-gpu-storage
            - mountPath: /dev/shm
              name: shm
            - mountPath: /etc/pki/tls/custom-certs
              name: trusted-ca
              readOnly: true
            - mountPath: /opt/app-root/pipeline-runtimes/
              name: runtime-images
          image: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-minimal-notebook:3.4'
          workingDir: /opt/app-root/src
        - resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8444
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: kube-rbac-proxy
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8444
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8443
              name: kube-rbac-proxy
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/kube-rbac-proxy
              name: kube-rbac-proxy-config
            - mountPath: /etc/tls/private
              name: kube-rbac-proxy-tls-certificates
          image: 'registry.redhat.io/rhoai/odh-kube-auth-proxy-rhel9@sha256:07ee0914946d9d6b2c7c7367be5b6bc13ddf0dddd93e896fc50aa617d761dc3a'
          args:
            - '--secure-listen-address=0.0.0.0:8443'
            - '--upstream=http://127.0.0.1:8888/'
            - '--logtostderr=true'
            - '--v=10'
            - '--proxy-endpoints-port=8444'
            - '--config-file=/etc/kube-rbac-proxy/config-file.yaml'
            - '--tls-cert-file=/etc/tls/private/tls.crt'
            - '--tls-private-key-file=/etc/tls/private/tls.key'
            - '--auth-header-fields-enabled=true'
            - '--auth-header-user-field-name=X-Auth-Request-User'
            - '--auth-header-groups-field-name=X-Auth-Request-Groups'
      enableServiceLinks: false
      nodeSelector:
        node.kubernetes.io/instance-type: g6.12xlarge
      serviceAccountName: wb-gpu
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Equal
          value: '100'
      volumes:
        - name: wb-gpu-storage
          persistentVolumeClaim:
            claimName: wb-gpu-storage
        - emptyDir:
            medium: Memory
          name: shm
        - configMap:
            name: workbench-trusted-ca-bundle
            optional: true
          name: trusted-ca
        - configMap:
            name: pipeline-runtime-images
            optional: true
          name: runtime-images
        - configMap:
            defaultMode: 420
            name: wb-gpu-kube-rbac-proxy-config
          name: kube-rbac-proxy-config
        - name: kube-rbac-proxy-tls-certificates
          secret:
            defaultMode: 420
            secretName: wb-gpu-kube-rbac-proxy-tls
status:
  conditions:
    - lastProbeTime: '2026-05-18T23:48:43Z'
      lastTransitionTime: '2026-05-18T23:48:36Z'
      status: 'True'
      type: PodReadyToStartContainers
    - lastProbeTime: '2026-05-18T23:48:43Z'
      lastTransitionTime: '2026-05-18T23:47:53Z'
      status: 'True'
      type: Initialized
    - lastProbeTime: '2026-05-18T23:48:43Z'
      lastTransitionTime: '2026-05-18T23:48:43Z'
      status: 'True'
      type: Ready
    - lastProbeTime: '2026-05-18T23:48:43Z'
      lastTransitionTime: '2026-05-18T23:48:43Z'
      status: 'True'
      type: ContainersReady
    - lastProbeTime: '2026-05-18T23:48:43Z'
      lastTransitionTime: '2026-05-18T23:47:53Z'
      status: 'True'
      type: PodScheduled
  containerState:
    running:
      startedAt: '2026-05-18T23:48:31Z'
  readyReplicas: 1
