apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-pod
  labels:
    app: pvc-test-pod
spec:
  restartPolicy: Always
  containers:
    - name: test-container
    # In a disconnected environment, you cannot use tag. Rather you will have to use SHA digest. 
    #For example, instead of using "registry.access.redhat.com/ubi9/ubi-minimal:latest", you would use "registry.access.redhat.com/ubi9/ubi-minimal@sha256:abc123...". 
      command:
        - /bin/sh
        - -c
        - |
          mkdir -p /mnt/testdata
          echo "container started" >> /mnt/testdata/startup.log
          sleep 365d
      volumeMounts:
        - name: test-storage
          mountPath: /mnt/testdata
  volumes:
    - name: test-storage
      persistentVolumeClaim:
        claimName: test-pvc