apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guidellm-results-pvc
  labels:
    app.kubernetes.io/name: guidellm-results-pvc
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi