apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc-model-download.yaml
  - configmap-model-download.yaml
  - secret-hf-token.example.yaml
  - pod-model-downloader.yaml
