apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-pvc
  labels:
    app.kubernetes.io/name: model-storage
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
