kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    openshift.io/description: Workbench Persistent Storage
    openshift.io/display-name: wb-gpu-storage
  name: wb-gpu-storage
  namespace: project-workbench-test
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem