apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: google-adk-agent

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - source-configmap.yaml
  - secret.example.yaml
  #- imagestream.yaml
  #- buildconfig.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
