apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: google-adk-agent

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - configmap-agent-files.yaml
  - secret.example.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
