apiVersion: v1
kind: Secret
metadata:
  name: google-adk-agent-secret
  namespace: google-adk-agent
  labels:
    app.kubernetes.io/name: google-adk-agent
    app.kubernetes.io/part-of: rhoai-demos
type: Opaque
stringData:
  OPENAI_API_KEY: EMPTY
